version: '3.8'

services:
  backend:
    build: ./backend
    container_name: ba_chatbot_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - ANONYMIZED_TELEMETRY=False
    volumes:
      - ./backend/chroma_db:/app/chroma_db
      - ./data:/data
    restart: always

  frontend:
    build: ./frontend
    container_name: ba_chatbot_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
